<a href="https://colab.research.google.com/github/hao-phan-cs/medium-docs/blob/master/numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Giới thiệu về NumPy

- NumPy là một thư viện của Python, sỡ hữu kiểu dữ liệu chính là NumPy array và các hàm hỗ trợ xử lí dữ liệu. Về cơ bản, NumPy arrays có bản chất tương tự như "list". Nhưng các phần tử có cùng kiểu dữ liệu và nó có các ưu điểm phục vụ cho việc thao tác, xử lí dữ liệu như nhanh hơn, tiện dụng hơn và tiêu hao ít bộ nhớ.
- NumPy rất hữu ích cho việc tính toán các mảng nhiều chiều, có kích thước lớn với các hàm số đã được tối ưu áp dụng lên các mảng nhiều chiều đó, đặc biệt là các hàm số liên quan tới Đại Số Tuyến Tính.

Sau khi đã cài đặt xong NumPy, chúng ta cần import nó để sử dụng như các thư viện khác của Python để sử dụng các hàm số của NumPy:




In [0]:
import numpy as np

## Khởi tạo mảng với NumPy

### np.array()

In [0]:
# khởi tạo mảng một chiều bằng hàm np.array()
x = np.array([1, 2, 3, 'a'])
print(x)

['1' '2' '3' 'a']


In [0]:
# kiểu dữ liệu numpy array
type(x)

numpy.ndarray

In [0]:
# kiểu dữ liệu của 1 phần tử trong numpy array
type(x[0])

numpy.str_

In [0]:
'''Todo: thử khai báo vector  x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]'''
# your code here 

[ 1  2  3  4  5  6  7  8  9 10]


In [0]:
# tạo mảng 2 chiều
np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [0]:
# tạo mảng 3 chiều
arr3d = np.array([[[1, 1], [2, 2]], [[3, 3], [4, 4]]])
print(arr3d)

[[[1 1]
  [2 2]]

 [[3 3]
  [4 4]]]


In [0]:
# chiều của mảng: trả về 1 tuple gồm n phần tử với n là số chiều của mảng
arr3d.shape

(2, 2, 2)

In [0]:
'''Todo: tạo 1 mảng 4 chiều với các phần tử số nguyên bất kì'''
# your code here

[[[[1 1]
   [2 2]]

  [[3 3]
   [4 4]]]


 [[[5 5]
   [6 6]]

  [[7 7]
   [8 8]]]]


### np.arange()

In [0]:
# tạo mảng theo cấp số cộng
print(np.arange(3)) # (0, <stop>)
print(np.arange(3, 10)) # (<start>, <stop>)
print(np.arange(3, 10, 3)) # (<start>, <stop>, <step>)

[0 1 2]
[3 4 5 6 7 8 9]
[3 6 9]


In [0]:
'''Xây dựng mảng các luỹ thừa của 2 nhỏ hơn 1025, bao gồm cả 1 = 2**0. 
Gợi ý: Nếu a là một mảng và b là một số thì b**a sẽ trả về một mảng cùng kích thước với a 
mà phần tử có chỉ số i bằng b**a[i], với ** là toán tử luỹ thừa.'''
# your code here

[   1    2    4    8   16   32   64  128  256  512 1024]


In [0]:
# tổng số phần tử của mảng === tích giá trị các chiều của mảng
arr = np.arange(0, 10, 3) # mảng 1 chiều chứa 4 phần tử
print(arr)
arr = arr.reshape(2, 2) # mảng 2 chiều, mỗi chiều chứa 2 phần tử
print(arr)

[0 3 6 9]
[[0 3]
 [6 9]]


In [0]:
'''Tạo mảng 1 chiều gồm 16 phần tử  (1, 2,...15, 16), sau đó chuyển thành dạng ma trận vuông 4x4'''
# your code here

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


### np.zeros(), np.ones() và np.full()

In [0]:
# Khởi tạo vector toàn chứa giá trị 0
arr0 = np.zeros(5)
# Khởi tạo vector toàn chứa giá trị 1
arr1 = np.ones(5)

# Khởi tạo vector toàn chứa giá trị được quy định
val = 10
arrVal = np.full(5, val)

print(arr0)
print(arr1)
print(arrVal)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[10 10 10 10 10]


In [0]:
# khởi tạo ma trận đơn vị kích thước 3x3
idMat = np.eye(3)
print(idMat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### np.random()

In [0]:
# tạo mảng 2 chiều có kích thước 2x3
print(np.random.random((2, 3)))

[[0.62458755 0.10245283 0.17433315]
 [0.42482323 0.04846587 0.42415937]]


## Array Indexing

###  Dùng chỉ số (Integer Array Indexing) và Slicing

In [0]:
a = np.array([[1,2,3,4], 
              [5,6,7,8], 
              [9,10,11,12]])

In [0]:
# Dùng chỉ số để lấy phần tử hàng 1, cột 2
print(a[1][2]) # 7
print(a[1, 2]) # 7

7
7


In [0]:
# Dùng slicing để lấy 2 hàng đầu tiên của 2 cột đầu tiên
print(a[:2][:2])

[[1 2 3 4]
 [5 6 7 8]]


In [0]:
# Kết hợp dùng slicing và dùng chỉ số
# Chú ý: sẽ tạo ra mảng có rank thấp hơn mảng cũ
r1 = a[1, :] # hàng 1 của a (mảng con này có rank là 1)
print(r1, r1.shape)

[5 6 7 8] (4,)


### Boolean Array Indexing

In [0]:
a = np.array([[1,2], [3, 4], [5, 6]])
bool_idx = (a > 2) # Tìm các phần tử lớn hơn 2;
# Trả về 1 numpy array of Booleans có shape như mảng a
# và giá trị tại mỗi phần tử là 
# True nếu phần tử của a tại đó > 2,
# False cho trường hợp ngược lại.
print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


## Các phép toán với NumPy arrays

### Các phép toán chỉ với một dòng code.

In [0]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print(x ** y)

[[1.0000e+00 6.4000e+01]
 [2.1870e+03 6.5536e+04]]


In [0]:
# Tổng của 2 mảng, cả 2 cách cho cùng một kết quả
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [0]:
# Hiệu 2 mảng
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [0]:
# Tính tích từng phần tử của x nhân với từng phần tử của y
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [0]:
# Tương tự thương của từng phần x chia với từng phần tử y
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [0]:
# Căn bậc 2 từng phần tử trong x
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


### Để nhân 2 ma trận hoặc nhân vector với ma trận trong numpy, chúng ta sử dụng hàm dot

In [0]:
x = np.array([[1,2],[3,4]]) # mảng rank 2 (ma trận)
y = np.array([[5,6],[7,8]]) # mảng rank 2 (ma trận)
v = np.array([9,10]) # mảng rank 1 (vector)
w = np.array([11, 12]) # mảng rank 1 (vector)

In [0]:
# Tích trong của 2 vector; Cả 2 đều cho kết quả là 219
print(v.dot(w))
print(np.dot(v, w))

219
219


In [0]:
# Nhân ma trận với vector; cả 2 đều cho mảng rank 1: [29 67]
print(x.dot(v))
print(np.dot(x, v))

[29 67]
[29 67]


In [0]:
# Ma trận với ma trận; cả 2 đều cho mảng rank 2
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


### Các hàm toán học khác:

Các hàm toán học như np.sum ,np.abs, np.log, np.exp, np.sin, np.cos, np.tan cũng áp dụng lên từng phần tử của mảng. Hàm np.log là logarit tự nhiên, hàm np.exp là hàm e^x.

In [0]:
# Ví dụ hàm sum
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Tổng các phần tử của mảng; prints "10"
print(np.sum(x, axis=0))  # Tính tổng theo từng cột; prints "[4 6]"
print(np.sum(x, axis=1))  # Tính tổng theo từng hàng; prints "[3 7]"

10
[4 6]
[3 7]


Để tìm giá trị lớn nhất hay nhỏ nhất của mảng một chiều, chúng ta đơn giản sử dụng hàm np.min hoặc np.max. Ví dụ:

In [0]:
a = np.arange(10)
a[-1] = -2 
print(np.min(a))
print(np.max(a))

-2
8


In [0]:
# hoặc:
print(a.min()) # -2
print(a.max()) # 8

-2
8


Để tìm chỉ số mà tại đó mảng một chiều đạt giá trị nhỏ nhất hay lớn nhất, ta có thể sử dụng np.argmin, hoặc np.argmax:

In [0]:
print(np.argmin(a))
print(np.argmax(a))

9
8


In [0]:
# hoặc:
print(a.argmin()) # 9
print(a.argmax()) # 8 

9
8


### Ma trận chuyển vị

In [0]:
# lấy ma trận chuyển vị bằng thuộc tính T
x = np.array([[1,2], [3,4]])
print(x)    
print(x.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


### Broadcasting

In [0]:
# Cộng vector v vào mỗi hàng của ma trận x,
# Lưu trữ kết quả trong ma trận y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Tự động cộng v vào từng hàng của x sử dụng broadcasting
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Todo: Cho một mảng 1 chiều x = [3, 5, 2, 1, 6]
tính mảng y và z sao cho y[i] = pi/2 - x[i] và z[i] = cos(x[i]) - sin(x[i]). Sau đó trả về tổng các phần tử của z

In [0]:
'''Todo: Cho một mảng 1 chiều x, tính mảng y và z sao cho y[i] = pi/2 - x[i] và z[i] = cos(x[i]) - sin(x[i]). Sau đó trả về tổng các phần tử của z'''
import math
pi = math.pi
x = np.array([3, 5, 2, 1, 6])
# your code here

y =  [-1.42920367 -3.42920367 -0.42920367  0.57079633 -4.42920367]
z =  [-0.84887249 -0.67526209  0.49315059  1.38177329  0.68075479]
